# Generated by Django 3.0.7 on 2020-06-28 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
